
def suggest_lawyer_type(input_text):
  
    keyword_mapping = {
    "divorce": "Family Lawyer",
    "criminal defense": "Criminal Defense Lawyer",
    "tax evasion": "Tax Lawyer",
    "contract dispute": "Contract Lawyer",
    "personal injury": "Personal Injury Lawyer",
    "real estate": "Real Estate Lawyer",
    "employment": "Employment Lawyer",
    "business incorporation": "Business Lawyer",
    "wills and estates": "Estate Planning Lawyer",
    "immigration": "Immigration Lawyer",
    "medical malpractice": "Medical Malpractice Lawyer",
    "intellectual property": "Intellectual Property Lawyer",
    "bankruptcy": "Bankruptcy Lawyer",
    "child custody": "Family Lawyer",
    "drug offenses": "Criminal Defense Lawyer",
    "estate planning": "Estate Planning Lawyer",
    "contract drafting": "Contract Lawyer",
    "auto accidents": "Personal Injury Lawyer",
    "property disputes": "Real Estate Lawyer",
    "wrongful termination": "Employment Lawyer",
    "business contracts": "Business Lawyer",
    "trusts and wills": "Estate Planning Lawyer",
    "visa and green card": "Immigration Lawyer",
    "birth injuries": "Medical Malpractice Lawyer",
    "patents and trademarks": "Intellectual Property Lawyer",
    "debt relief": "Bankruptcy Lawyer",
    "adoption and guardianship": "Family Lawyer",
    "assault and battery": "Criminal Defense Lawyer",
    "tax planning": "Tax Lawyer",
    "breach of contract": "Contract Lawyer",
    "workers' compensation": "Personal Injury Lawyer",
    "landlord-tenant disputes": "Real Estate Lawyer",
    "discrimination claims": "Employment Lawyer",
    "corporate law": "Business Lawyer",
    "probate matters": "Estate Planning Lawyer",
    "citizenship and naturalization": "Immigration Lawyer",
    "nursing home abuse": "Medical Malpractice Lawyer",
    "copyright and patents": "Intellectual Property Lawyer",
    "foreclosure defense": "Bankruptcy Lawyer",
    "child support and custody": "Family Lawyer",
    "white-collar crimes": "Criminal Defense Lawyer",
    "estate administration": "Estate Planning Lawyer",
    "commercial contracts": "Contract Lawyer",
    "dog bite injuries": "Personal Injury Lawyer",
    "real estate transactions": "Real Estate Lawyer",
    "sexual harassment": "Employment Lawyer",
    "mergers and acquisitions": "Business Lawyer",
    "elder law": "Estate Planning Lawyer",
    "asylum and refugee status": "Immigration Lawyer",
    "product liability": "Personal Injury Lawyer",
    "entertainment law": "Intellectual Property Lawyer",
    "credit repair": "Bankruptcy Lawyer",
    "prenuptial agreements": "Family Lawyer",
    "fraud and embezzlement": "Criminal Defense Lawyer",
    "estate litigation": "Estate Planning Lawyer",
    "insurance claims": "Personal Injury Lawyer",
    "construction law": "Real Estate Lawyer",
    "overtime and wage disputes": "Employment Lawyer",
    "startup and small business law": "Business Lawyer",
    "living wills and advance directives": "Estate Planning Lawyer",
    "deportation defense": "Immigration Lawyer",
    "wrongful death": "Personal Injury Lawyer",
    "trade secrets": "Intellectual Property Lawyer",
    "debt collection defense": "Bankruptcy Lawyer",
    "adoption law": "Family Lawyer",
    "homicide defense": "Criminal Defense Lawyer",
    "inheritance disputes": "Estate Planning Lawyer",
    "workers' rights": "Employment Lawyer",
    "corporate governance": "Business Lawyer",
    "guardianship and conservatorship": "Estate Planning Lawyer",
    "visa appeals": "Immigration Lawyer",
    "medical negligence": "Medical Malpractice Lawyer",
    "cybersecurity and data privacy": "Intellectual Property Lawyer",
    "mortgage modification": "Real Estate Lawyer",
    "age discrimination": "Employment Lawyer",
    "intellectual property litigation": "Intellectual Property Lawyer",
    "student loan debt": "Bankruptcy Lawyer",
    "domestic violence": "Family Lawyer",
    "sexual assault defense": "Criminal Defense Lawyer",
    "trust administration": "Estate Planning Lawyer",
    "workers' compensation appeals": "Personal Injury Lawyer",
    "zoning and land use": "Real Estate Lawyer",
    "whistleblower protection": "Employment Lawyer",
    "business formation": "Business Lawyer",
    "elder abuse": "Estate Planning Lawyer",
    "immigration appeals": "Immigration Lawyer",
    "nursing license defense": "Medical Malpractice Lawyer",
    "trademark registration": "Intellectual Property Lawyer",
    "chapter 7 bankruptcy": "Bankruptcy Lawyer",
    "child abuse and neglect": "Family Lawyer",
    "fraud defense": "Criminal Defense Lawyer",
    "estate planning for blended families": "Estate Planning Lawyer",
    "overtime pay": "Employment Lawyer",
    "contract disputes in construction": "Real Estate Lawyer",
    "intellectual property transactions": "Intellectual Property Lawyer",
    "chapter 13 bankruptcy": "Bankruptcy Lawyer",
    "adoption assistance": "Family Lawyer",
    "misdemeanor defense": "Criminal Defense Lawyer",
    "probate court litigation": "Estate Planning Lawyer",
    "hostile work environment": "Employment Lawyer",
    "franchise law": "Business Lawyer",
    "special needs planning": "Estate Planning Lawyer",
    "visa petitions": "Immigration Lawyer",
    "birth certificate corrections": "Family Lawyer",
    "felony defense": "Criminal Defense Lawyer",
    "inheritance tax planning": "Estate Planning Lawyer",
    "employment discrimination": "Employment Lawyer",
    "real estate development": "Real Estate Lawyer",
    "intellectual property prosecution": "Intellectual Property Lawyer",
    "foreclosure alternatives": "Bankruptcy Lawyer",
    "child custody modifications": "Family Lawyer",
    "dui defense": "Criminal Defense Lawyer",
    "probate estate administration": "Estate Planning Lawyer",
    "sexual orientation discrimination": "Employment Lawyer",
    "small claims court": "Business Lawyer",
    "guardianship disputes": "Estate Planning Lawyer",
    "business contracts and agreements": "Contract Lawyer",
    "immigration court": "Immigration Lawyer",
    "spousal support and alimony": "Family Lawyer",
    "embezzlement defense": "Criminal Defense Lawyer",
    "family limited partnerships": "Estate Planning Lawyer",
    "wrongful termination claims": "Employment Lawyer",
    "real estate finance": "Real Estate Lawyer",
    "intellectual property licensing": "Intellectual Property Lawyer",
    "tax fraud defense": "Tax Lawyer",
    "adoption finalization": "Family Lawyer",
    "identity theft defense": "Criminal Defense Lawyer",
    "healthcare power of attorney": "Estate Planning Lawyer",
    "workers' compensation settlements": "Personal Injury Lawyer",
    "landlord-tenant law": "Real Estate Lawyer",
    "class action lawsuits": "Employment Lawyer",
    "business dissolution": "Business Lawyer",
    "elder law mediation": "Estate Planning Lawyer",
    "investor visas": "Immigration Lawyer",
    "spinal cord injuries": "Personal Injury Lawyer",
    "trade secrets protection": "Intellectual Property Lawyer",
    "business bankruptcy": "Bankruptcy Lawyer",
    "international adoption": "Family Lawyer",
    "assault defense": "Criminal Defense Lawyer",
    "estate planning for same-sex couples": "Estate Planning Lawyer",
    "workers' compensation claims": "Personal Injury Lawyer",
    "real estate leasing": "Real Estate Lawyer",
    "disability discrimination": "Employment Lawyer",
    "non-disclosure agreements": "Business Lawyer",
    "guardianship termination": "Estate Planning Lawyer",
    "immigration detention": "Immigration Lawyer",
    "brain injuries": "Personal Injury Lawyer",
    "copyright infringement defense": "Intellectual Property Lawyer",
    "chapter 11 bankruptcy": "Bankruptcy Lawyer",
    "adoption mediation": "Family Lawyer",
    "federal criminal defense": "Criminal Defense Lawyer",
    "trust fund planning": "Estate Planning Lawyer",
    "unpaid wages": "Employment Lawyer",
    "real estate litigation": "Real Estate Lawyer",
    "civil rights claims": "Personal Injury Lawyer",
    "trade secrets litigation": "Intellectual Property Lawyer",
    "business litigation": "Business Lawyer",
    "elder law litigation": "Estate Planning Lawyer",
    "immigration removal proceedings": "Immigration Lawyer",
    "nursing home negligence": "Personal Injury Lawyer",
    "patent prosecution": "Intellectual Property Lawyer",
    "consumer bankruptcy": "Bankruptcy Lawyer",
    "child neglect defense": "Family Lawyer",
    "domestic partnerships": "Family Lawyer",
    "child visitation disputes": "Family Lawyer",
    "debt settlement": "Bankruptcy Lawyer",
    "misdemeanor expungement": "Criminal Defense Lawyer",
    "probate estate planning": "Estate Planning Lawyer",
    "employee benefits": "Employment Lawyer",
    "real estate zoning and permitting": "Real Estate Lawyer",
    "product liability defense": "Personal Injury Lawyer",
    "business taxation": "Tax Lawyer",
    "intellectual property enforcement": "Intellectual Property Lawyer",
    "estate tax planning": "Estate Planning Lawyer",
    "asylum applications": "Immigration Lawyer",
    "defamation defense": "Criminal Defense Lawyer",
    "domestic violence restraining orders": "Family Lawyer",
    "marital property division": "Family Lawyer",
    "child protective services": "Family Lawyer",
    "debt collection harassment": "Bankruptcy Lawyer",
    "wage and hour claims": "Employment Lawyer",
    "real estate title disputes": "Real Estate Lawyer",
    "oil and gas law": "Real Estate Lawyer",
    "environmental law": "Environmental Lawyer",
    "wrongful termination defense": "Employment Lawyer",
    "startup funding": "Business Lawyer",
    "construction defects": "Real Estate Lawyer",
    "intellectual property due diligence": "Intellectual Property Lawyer",
    "foreign investment visas": "Immigration Lawyer",
    "spousal support modification": "Family Lawyer",
    "cyberbullying defense": "Criminal Defense Lawyer",
    "probate estate disputes": "Estate Planning Lawyer",
    "employee contracts": "Employment Lawyer",
    "international business contracts": "Business Lawyer",
    "adoption subsidies": "Family Lawyer",
    "fraudulent conveyance defense": "Bankruptcy Lawyer",
    "estate planning for blended families": "Estate Planning Lawyer",
    "real estate closings": "Real Estate Lawyer",
    "wrongful death claims": "Personal Injury Lawyer",
    "intellectual property rights": "Intellectual Property Lawyer",
    "tax evasion defense": "Tax Lawyer",
    "divorce mediation": "Family Lawyer",
    "sex crimes defense": "Criminal Defense Lawyer",
    "guardianship administration": "Estate Planning Lawyer",
    "workers' compensation hearings": "Personal Injury Lawyer",
    "real estate foreclosures": "Real Estate Lawyer",
    "class action defense": "Business Lawyer",
    "employer immigration compliance": "Immigration Lawyer",
    "concussions and head injuries": "Personal Injury Lawyer",
    "copyright registration": "Intellectual Property Lawyer",
    "chapter 13 bankruptcy": "Bankruptcy Lawyer",
    "adoption home studies": "Family Lawyer",
    "drug possession defense": "Criminal Defense Lawyer",
    "trustee services": "Estate Planning Lawyer",
    "employment discrimination defense": "Employment Lawyer",
    "real estate eminent domain": "Real Estate Lawyer",
    "wrongful termination litigation": "Employment Lawyer",
    "business mergers": "Business Lawyer",
    "elder abuse prevention": "Estate Planning Lawyer",
    "immigration benefits": "Immigration Lawyer",
    "spinal injuries": "Personal Injury Lawyer",
    "trade secrets registration": "Intellectual Property Lawyer",
    "business contracts and negotiations": "Business Lawyer",
    "debt collection defense": "Bankruptcy Lawyer",
    "adoption agencies": "Family Lawyer",
    "homicide charges": "Criminal Defense Lawyer",
    "estate planning for children": "Estate Planning Lawyer",
    "workers' compensation insurance": "Personal Injury Lawyer",
    "real estate escrow": "Real Estate Lawyer",
    "non-compete agreements": "Employment Lawyer",
    "guardianship litigation": "Estate Planning Lawyer",
    "immigration consular processing": "Immigration Lawyer",
    "nursing home abuse claims": "Personal Injury Lawyer",
    "patent litigation": "Intellectual Property Lawyer",
    "corporate bankruptcy": "Bankruptcy Lawyer",
    "adoption disruption": "Family Lawyer",
    "sexual harassment claims": "Employment Lawyer",
    "business partnership disputes": "Business Lawyer",
    "elder financial abuse": "Estate Planning Lawyer",
    "immigration waivers": "Immigration Lawyer",
    "traumatic brain injuries": "Personal Injury Lawyer",
    "trademark disputes": "Intellectual Property Lawyer",
    "business startups": "Business Lawyer",
    "debt relief options": "Bankruptcy Lawyer",
    "child custody battles": "Family Lawyer",
    "aggravated assault defense": "Criminal Defense Lawyer",
    "estate planning for grandparents": "Estate Planning Lawyer",
    "workers' compensation settlements": "Personal Injury Lawyer",
    "real estate environmental law": "Real Estate Lawyer",
    "class action settlements": "Employment Lawyer",
    "business dissolution": "Business Lawyer",
    "elder law mediation": "Estate Planning Lawyer",
    "immigration court": "Immigration Lawyer",
    "brain injury claims": "Personal Injury Lawyer",
    "copyright infringement litigation": "Intellectual Property Lawyer",
    "chapter 11 bankruptcy": "Bankruptcy Lawyer",
    "adoption mediation": "Family Lawyer",
    "federal criminal defense": "Criminal Defense Lawyer",
    "trust fund planning": "Estate Planning Lawyer",
    "unpaid wages": "Employment Lawyer",
    "real estate litigation": "Real Estate Lawyer",
    "civil rights claims": "Personal Injury Lawyer",
    "trade secrets litigation": "Intellectual Property Lawyer",
    "business litigation": "Business Lawyer",
    "elder law litigation": "Estate Planning Lawyer",
    "immigration removal proceedings": "Immigration Lawyer",
    "nursing home negligence": "Personal Injury Lawyer",
    "patent prosecution": "Intellectual Property Lawyer",
    "consumer bankruptcy": "Bankruptcy Lawyer",
    "child neglect defense": "Family Lawyer",
    "domestic partnerships": "Family Lawyer",
    "child visitation disputes": "Family Lawyer",
    "debt settlement": "Bankruptcy Lawyer",
    "misdemeanor expungement": "Criminal Defense Lawyer",
    "probate estate planning": "Estate Planning Lawyer",
    "employee benefits": "Employment Lawyer",
    "real estate zoning and permitting": "Real Estate Lawyer",
    "product liability defense": "Personal Injury Lawyer",
    "business taxation": "Tax Lawyer",
    "intellectual property enforcement": "Intellectual Property Lawyer",
    "estate tax planning": "Estate Planning Lawyer",
    "asylum applications": "Immigration Lawyer",
    "defamation defense": "Criminal Defense Lawyer",
    "domestic violence restraining orders": "Family Lawyer",
    "marital property division": "Family Lawyer",
    "child protective services": "Family Lawyer",
    "debt collection harassment": "Bankruptcy Lawyer",
    "wage and hour claims": "Employment Lawyer",
    "real estate title disputes": "Real Estate Lawyer",
    "oil and gas law": "Real Estate Lawyer",
    "environmental law": "Environmental Lawyer",
    "wrongful termination defense": "Employment Lawyer",
    "startup funding": "Business Lawyer",
    "construction defects": "Real Estate Lawyer",
    "intellectual property due diligence": "Intellectual Property Lawyer",
    "foreign investment visas": "Immigration Lawyer",
    "spousal support modification": "Family Lawyer",
    "cyberbullying defense": "Criminal Defense Lawyer",
    "probate estate disputes": "Estate Planning Lawyer",
    "employee contracts": "Employment Lawyer",
    "international business contracts": "Business Lawyer",
    "adoption subsidies": "Family Lawyer",
    "fraudulent conveyance defense": "Bankruptcy Lawyer",
    "estate planning for blended families": "Estate Planning Lawyer",
    "real estate closings": "Real Estate Lawyer",
    "wrongful death claims": "Personal Injury Lawyer",
    "intellectual property rights": "Intellectual Property Lawyer",
    "tax evasion defense": "Tax Lawyer",
    "divorce mediation": "Family Lawyer",
    "sex crimes defense": "Criminal Defense Lawyer",
    "guardianship administration": "Estate Planning Lawyer",
    "workers' compensation hearings": "Personal Injury Lawyer",
    "real estate foreclosures": "Real Estate Lawyer",
    "class action defense": "Business Lawyer",
    "employer immigration compliance": "Immigration Lawyer",
    "concussions and head injuries": "Personal Injury Lawyer",
    "copyright registration": "Intellectual Property Lawyer",
    "chapter 13 bankruptcy": "Bankruptcy Lawyer",
    "adoption home studies": "Family Lawyer",
    "drug possession defense": "Criminal Defense Lawyer",
    "trustee services": "Estate Planning Lawyer",
    "employment discrimination defense": "Employment Lawyer",
    "real estate eminent domain": "Real Estate Lawyer",
    "wrongful termination litigation": "Employment Lawyer",
    "business mergers": "Business Lawyer",
    "elder abuse prevention": "Estate Planning Lawyer",
    "immigration benefits": "Immigration Lawyer",
    "spinal injuries": "Personal Injury Lawyer",
    "trade secrets registration": "Intellectual Property Lawyer",
    "business contracts and negotiations": "Business Lawyer",
    "debt collection defense": "Bankruptcy Lawyer",
    "adoption agencies": "Family Lawyer",
    "homicide charges": "Criminal Defense Lawyer",
    "estate planning for children": "Estate Planning Lawyer",
    "workers' compensation insurance": "Personal Injury Lawyer",
    "real estate escrow": "Real Estate Lawyer",
    "non-compete agreements": "Employment Lawyer",
    "guardianship litigation": "Estate Planning Lawyer",
    "immigration consular processing": "Immigration Lawyer",
    "nursing home abuse claims": "Personal Injury Lawyer",
    "patent litigation": "Intellectual Property Lawyer",
    "corporate bankruptcy": "Bankruptcy Lawyer",
    "adoption disruption": "Family Lawyer",
    "sexual harassment claims": "Employment Lawyer",
    "business partnership disputes": "Business Lawyer",
    "elder financial abuse": "Estate Planning Lawyer",
    "immigration waivers": "Immigration Lawyer",
    "traumatic brain injuries": "Personal Injury Lawyer",
    "trademark disputes": "Intellectual Property Lawyer",
    "business startups": "Business Lawyer",
    "debt relief options": "Bankruptcy Lawyer",
    "child custody battles": "Family Lawyer",
    "aggravated assault defense": "Criminal Defense Lawyer",
    "estate planning for grandparents": "Estate Planning Lawyer",
    "workers' compensation settlements": "Personal Injury Lawyer",
    "real estate environmental law": "Real Estate Lawyer",
    "class action settlements": "Employment Lawyer",
    "business dissolution": "Business Lawyer",
    "elder law mediation": "Estate Planning Lawyer",
    "immigration court": "Immigration Lawyer",
    "brain injury claims": "Personal Injury Lawyer",
    "copyright infringement litigation": "Intellectual Property Lawyer",
    "chapter 11 bankruptcy": "Bankruptcy Lawyer",
    "adoption mediation": "Family Lawyer",
    "federal criminal defense": "Criminal Defense Lawyer",
    "trust fund planning": "Estate Planning Lawyer",
    "unpaid wages": "Employment Lawyer",
    "real estate litigation": "Real Estate Lawyer",
    "civil rights claims": "Personal Injury Lawyer",
    "trade secrets litigation": "Intellectual Property Lawyer",
    "business litigation": "Business Lawyer",
    "elder law litigation": "Estate Planning Lawyer",
    "immigration removal proceedings": "Immigration Lawyer",
    "nursing home negligence": "Personal Injury Lawyer",
    "patent prosecution": "Intellectual Property Lawyer",
    "consumer bankruptcy": "Bankruptcy Lawyer",
    "child neglect defense": "Family Lawyer",
    "domestic partnerships": "Family Lawyer",
    "child visitation disputes": "Family Lawyer",
    "debt settlement": "Bankruptcy Lawyer",
    "misdemeanor expungement": "Criminal Defense Lawyer",
    "probate estate planning": "Estate Planning Lawyer",
    "employee benefits": "Employment Lawyer",
    "real estate zoning and permitting": "Real Estate Lawyer",
    "product liability defense": "Personal Injury Lawyer",
    "business taxation": "Tax Lawyer",
    "intellectual property enforcement": "Intellectual Property Lawyer",
    "estate tax planning": "Estate Planning Lawyer",
    "asylum applications": "Immigration Lawyer",
    "defamation defense": "Criminal Defense Lawyer",
    "domestic violence restraining orders": "Family Lawyer",
    "marital property division": "Family Lawyer",
    "child protective services": "Family Lawyer",
    "debt collection harassment": "Bankruptcy Lawyer",
    "wage and hour claims": "Employment Lawyer",
    "real estate title disputes": "Real Estate Lawyer",
    "oil and gas law": "Real Estate Lawyer",
    "environmental law": "Environmental Lawyer",
    "wrongful termination defense": "Employment Lawyer",
    "startup funding": "Business Lawyer",
    "construction defects": "Real Estate Lawyer",
    "intellectual property due diligence": "Intellectual Property Lawyer",
    "foreign investment visas": "Immigration Lawyer",
    "spousal support modification": "Family Lawyer",
    "cyberbullying defense": "Criminal Defense Lawyer",
    "probate estate disputes": "Estate Planning Lawyer",
    "employee contracts": "Employment Lawyer",
    "international business contracts": "Business Lawyer",
    "adoption subsidies": "Family Lawyer",
    "fraudulent conveyance defense": "Bankruptcy Lawyer",
    "estate planning for blended families": "Estate Planning Lawyer",
    "real estate closings": "Real Estate Lawyer",
    "wrongful death claims": "Personal Injury Lawyer",
    "intellectual property rights": "Intellectual Property Lawyer",
    "tax evasion defense": "Tax Lawyer",
    "divorce mediation": "Family Lawyer",
    "sex crimes defense": "Criminal Defense Lawyer",
    "guardianship administration": "Estate Planning Lawyer",
    "workers' compensation hearings": "Personal Injury Lawyer",
    "real estate foreclosures": "Real Estate Lawyer",
    "class action defense": "Business Lawyer",
    "employer immigration compliance": "Immigration Lawyer",
    "concussions and head injuries": "Personal Injury Lawyer",
    "copyright registration": "Intellectual Property Lawyer",
    "chapter 13 bankruptcy": "Bankruptcy Lawyer",
    "adoption home studies": "Family Lawyer",
    "drug possession defense": "Criminal Defense Lawyer",
    "trustee services": "Estate Planning Lawyer",
    "employment discrimination defense": "Employment Lawyer",
    "real estate eminent domain": "Real Estate Lawyer",
    "wrongful termination litigation": "Employment Lawyer",
    "business mergers": "Business Lawyer",
    "elder abuse prevention": "Estate Planning Lawyer",
    "immigration benefits": "Immigration Lawyer",
    "spinal injuries": "Personal Injury Lawyer",
    "trade secrets registration": "Intellectual Property Lawyer",
    "business contracts and negotiations": "Business Lawyer",
    "debt collection defense": "Bankruptcy Lawyer",
    "adoption agencies": "Family Lawyer",
    "homicide charges": "Criminal Defense Lawyer",
    "estate planning for children": "Estate Planning Lawyer",
    "workers' compensation insurance": "Personal Injury Lawyer",
    "real estate escrow": "Real Estate Lawyer",
    "non-compete agreements": "Employment Lawyer",
    "guardianship litigation": "Estate Planning Lawyer",
    "immigration consular processing": "Immigration Lawyer",
    "nursing home abuse claims": "Personal Injury Lawyer",
    "patent litigation": "Intellectual Property Lawyer",
    "corporate bankruptcy": "Bankruptcy Lawyer",
    "adoption disruption": "Family Lawyer",
    "sexual harassment claims": "Employment Lawyer",
    "business partnership disputes": "Business Lawyer",
    "elder financial abuse": "Estate Planning Lawyer",
    "immigration waivers": "Immigration Lawyer",
    "traumatic brain injuries": "Personal Injury Lawyer",
    "trademark disputes": "Intellectual Property Lawyer",
    "business startups": "Business Lawyer",
    "debt relief options": "Bankruptcy Lawyer",
    "child custody battles": "Family Lawyer",
    "aggravated assault defense": "Criminal Defense Lawyer",
    "estate planning for grandparents": "Estate Planning Lawyer",
    "workers' compensation settlements": "Personal Injury Lawyer",
    "real estate environmental law": "Real Estate Lawyer",
    "class action settlements": "Employment Lawyer",
    "business dissolution": "Business Lawyer",
    "elder law mediation": "Estate Planning Lawyer",
    "immigration court": "Immigration Lawyer",
    "brain injury claims": "Personal Injury Lawyer",
    "copyright infringement litigation": "Intellectual Property Lawyer",
    "chapter 11 bankruptcy": "Bankruptcy Lawyer",
    "adoption mediation": "Family Lawyer",
    "federal criminal defense": "Criminal Defense Lawyer",
    "trust fund planning": "Estate Planning Lawyer",
    "unpaid wages": "Employment Lawyer",
    "real estate litigation": "Real Estate Lawyer",
    "civil rights claims": "Personal Injury Lawyer",
    "trade secrets litigation": "Intellectual Property Lawyer",
    "business litigation": "Business Lawyer",
    "elder law litigation": "Estate Planning Lawyer",
    "immigration removal proceedings": "Immigration Lawyer",
    "nursing home negligence": "Personal Injury Lawyer",
    "patent prosecution": "Intellectual Property Lawyer",
    "consumer bankruptcy": "Bankruptcy Lawyer",
    "child neglect defense": "Family Lawyer",
    "domestic partnerships": "Family Lawyer",
    "child visitation disputes": "Family Lawyer",
    "debt settlement": "Bankruptcy Lawyer",
    "misdemeanor expungement": "Criminal Defense Lawyer",
    "probate estate planning": "Estate Planning Lawyer",
    "employee benefits": "Employment Lawyer",
    "real estate zoning and permitting": "Real Estate Lawyer",
    "product liability defense": "Personal Injury Lawyer",
    "business taxation": "Tax Lawyer",
    "intellectual property enforcement": "Intellectual Property Lawyer",
    "estate tax planning": "Estate Planning Lawyer",
    "asylum applications": "Immigration Lawyer",
    "defamation defense": "Criminal Defense Lawyer",
    "domestic violence restraining orders": "Family Lawyer",
    "marital property division": "Family Lawyer",
    "child protective services": "Family Lawyer",
    "debt collection harassment": "Bankruptcy Lawyer",
    "wage and hour claims": "Employment Lawyer",
    "real estate title disputes": "Real Estate Lawyer",
    "oil and gas law": "Real Estate Lawyer",
    "environmental law": "Environmental Lawyer",
    "wrongful termination defense": "Employment Lawyer",
    "startup funding": "Business Lawyer",
    "construction defects": "Real Estate Lawyer",
    "intellectual property due diligence": "Intellectual Property Lawyer",
    "foreign investment visas": "Immigration Lawyer",
    "spousal support modification": "Family Lawyer",
    "cyberbullying defense": "Criminal Defense Lawyer",
    "probate estate disputes": "Estate Planning Lawyer",
    "employee contracts": "Employment Lawyer",
    "international business contracts": "Business Lawyer",
    "adoption subsidies": "Family Lawyer",
    "fraudulent conveyance defense": "Bankruptcy Lawyer",
    "estate planning for blended families": "Estate Planning Lawyer",
    "real estate closings": "Real Estate Lawyer",
    "wrongful death claims": "Personal Injury Lawyer",
    "intellectual property rights": "Intellectual Property Lawyer",
    "tax evasion defense": "Tax Lawyer",
    "divorce mediation": "Family Lawyer",
    "sex crimes defense": "Criminal Defense Lawyer",
    "guardianship administration": "Estate Planning Lawyer",
    "workers' compensation hearings": "Personal Injury Lawyer",
    "real estate foreclosures": "Real Estate Lawyer",
    "class action defense": "Business Lawyer",
    "employer immigration compliance": "Immigration Lawyer",
    "concussions and head injuries": "Personal Injury Lawyer",
    "copyright registration": "Intellectual Property Lawyer",
    "chapter 13 bankruptcy": "Bankruptcy Lawyer",
    "adoption home studies": "Family Lawyer",
    "drug possession defense": "Criminal Defense Lawyer",
    "trustee services": "Estate Planning Lawyer",
    "employment discrimination defense": "Employment Lawyer",
    "real estate eminent domain": "Real Estate Lawyer",
    "wrongful termination litigation": "Employment Lawyer",
    "business mergers": "Business Lawyer",
    "elder abuse prevention": "Estate Planning Lawyer",
    "immigration benefits": "Immigration Lawyer",
    "spinal injuries": "Personal Injury Lawyer",
    "trade secrets registration": "Intellectual Property Lawyer",
    "business contracts and negotiations": "Business Lawyer",
    "debt collection defense": "Bankruptcy Lawyer",
    "adoption agencies": "Family Lawyer",
    "homicide charges": "Criminal Defense Lawyer",
    "estate planning for children": "Estate Planning Lawyer",
    "workers' compensation insurance": "Personal Injury Lawyer",
    "real estate escrow": "Real Estate Lawyer",
    "non-compete agreements": "Employment Lawyer",
    "guardianship litigation": "Estate Planning Lawyer",
    "immigration consular processing": "Immigration Lawyer",
    "nursing home abuse claims": "Personal Injury Lawyer",
    "patent litigation": "Intellectual Property Lawyer",
    "corporate bankruptcy": "Bankruptcy Lawyer",
    "adoption disruption": "Family Lawyer",
    "sexual harassment claims": "Employment Lawyer",
    "business partnership disputes": "Business Lawyer",
    "elder financial abuse": "Estate Planning Lawyer",
    "immigration waivers": "Immigration Lawyer",
    "traumatic brain injuries": "Personal Injury Lawyer",
    "trademark disputes": "Intellectual Property Lawyer",
    "business startups": "Business Lawyer",
    "debt relief options": "Bankruptcy Lawyer",
    "child custody battles": "Family Lawyer",
    "aggravated assault defense": "Criminal Defense Lawyer",
    "estate planning for grandparents": "Estate Planning Lawyer",
    "workers' compensation settlements": "Personal Injury Lawyer",
    "real estate environmental law": "Real Estate Lawyer",
    "class action settlements": "Employment Lawyer",
    "business dissolution": "Business Lawyer",
    "elder law mediation": "Estate Planning Lawyer",
    "immigration court": "Immigration Lawyer",
    "brain injury claims": "Personal Injury Lawyer",
    "copyright infringement litigation": "Intellectual Property Lawyer",
    "chapter 11 bankruptcy": "Bankruptcy Lawyer",
    "adoption mediation": "Family Lawyer",
    "federal criminal defense": "Criminal Defense Lawyer",
    "trust fund planning": "Estate Planning Lawyer",
    "unpaid wages": "Employment Lawyer",
    "real estate litigation": "Real Estate Lawyer",
    "civil rights claims": "Personal Injury Lawyer",
    "trade secrets litigation": "Intellectual Property Lawyer",
    "business litigation": "Business Lawyer",
    "elder law litigation": "Estate Planning Lawyer",
    "immigration removal proceedings": "Immigration Lawyer",
    "nursing home negligence": "Personal Injury Lawyer",
    "patent prosecution": "Intellectual Property Lawyer",
    "consumer bankruptcy": "Bankruptcy Lawyer",
    "child neglect defense": "Family Lawyer",
    "domestic partnerships": "Family Lawyer",
    "child visitation disputes": "Family Lawyer",
    "debt settlement": "Bankruptcy Lawyer",
    "misdemeanor expungement": "Criminal Defense Lawyer",
    "probate estate planning": "Estate Planning Lawyer",
    "employee benefits": "Employment Lawyer",
    "real estate zoning and permitting": "Real Estate Lawyer",
    "product liability defense": "Personal Injury Lawyer",
    "business taxation": "Tax Lawyer",
    "intellectual property enforcement": "Intellectual Property Lawyer",
    "estate tax planning": "Estate Planning Lawyer",
    "asylum applications": "Immigration Lawyer",
    "defamation defense": "Criminal Defense Lawyer",
    "domestic violence restraining orders": "Family Lawyer",
    "marital property division": "Family Lawyer",
    "child protective services": "Family Lawyer",
    "debt collection harassment": "Bankruptcy Lawyer",
    "wage and hour claims": "Employment Lawyer",
    "real estate title disputes": "Real Estate Lawyer",
    "oil and gas law": "Real Estate Lawyer",
    "environmental law": "Environmental Lawyer",
    "wrongful termination defense": "Employment Lawyer",
    "startup funding": "Business Lawyer",
    "construction defects": "Real Estate Lawyer",
    "intellectual property due diligence": "Intellectual Property Lawyer",
    "foreign investment visas": "Immigration Lawyer",
    "spousal support modification": "Family Lawyer",
    "cyberbullying defense": "Criminal Defense Lawyer",
    "probate estate disputes": "Estate Planning Lawyer",
    "employee contracts": "Employment Lawyer",
    "international business contracts": "Business Lawyer",
    "adoption subsidies": "Family Lawyer",
    "fraudulent conveyance defense": "Bankruptcy Lawyer",
    "estate planning for blended families": "Estate Planning Lawyer",
    "real estate closings": "Real Estate Lawyer",
    "wrongful death claims": "Personal Injury Lawyer",
    "intellectual property rights": "Intellectual Property Lawyer",
    "tax evasion defense": "Tax Lawyer",
    "divorce mediation": "Family Lawyer",
    "sex crimes defense": "Criminal Defense Lawyer",
    "guardianship administration": "Estate Planning Lawyer",
    "workers' compensation hearings": "Personal Injury Lawyer",
    "real estate foreclosures": "Real Estate Lawyer",
    "class action defense": "Business Lawyer",
    "employer immigration compliance": "Immigration Lawyer",
    "concussions and head injuries": "Personal Injury Lawyer",
    "copyright registration": "Intellectual Property Lawyer",
    "chapter 13 bankruptcy": "Bankruptcy Lawyer",
    "adoption home studies": "Family Lawyer",
    "drug possession defense": "Criminal Defense Lawyer",
    "trustee services": "Estate Planning Lawyer",
    "employment discrimination defense": "Employment Lawyer",
    "real estate eminent domain": "Real Estate Lawyer",
    "wrongful termination litigation": "Employment Lawyer",
    "business mergers": "Business Lawyer",
    "elder abuse prevention": "Estate Planning Lawyer",
    "immigration benefits": "Immigration Lawyer",
    "spinal injuries": "Personal Injury Lawyer",
    "trade secrets registration": "Intellectual Property Lawyer",
    "business contracts and negotiations": "Business Lawyer",
    "debt collection defense": "Bankruptcy Lawyer",
    "adoption agencies": "Family Lawyer",
    "homicide charges": "Criminal Defense Lawyer",
    "estate planning for children": "Estate Planning Lawyer",
    "workers' compensation insurance": "Personal Injury Lawyer",
    "real estate escrow": "Real Estate Lawyer",
    "non-compete agreements": "Employment Lawyer",
    "guardianship litigation": "Estate Planning Lawyer",
    "immigration consular processing": "Immigration Lawyer",
    "nursing home abuse claims": "Personal Injury Lawyer",
    "patent litigation": "Intellectual Property Lawyer",
    "corporate bankruptcy": "Bankruptcy"
    }

   
    suggested_lawyer_type = None

   
    for keyword, lawyer_type in keyword_mapping.items():
        if keyword in input_text.lower():
            suggested_lawyer_type = lawyer_type
            break 

    return suggested_lawyer_type

if __name__ == "__main__":
    input_text = "patent litigation."
    suggested_lawyer = suggest_lawyer_type(input_text)

    if suggested_lawyer:
        print("Hello Sir/Ma'am, Thank You for using ourservices. Based on your input you may need a", suggested_lawyer)
    else:
        print("No specific lawyer type suggested for this input.")
